# Site settings
title: Tristen Bressler
url: https://TristenBressler.github.io
description: "Project Engineer|CEO|Business Owner|Award-Winning National Artist|Vitalist"
keywords: "your keywords, separated by commas"
skills: "Solutions - Resilience - Content"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  social: Around the Web
 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Instagram
    url: 
  - title: Snapchat
    url:
  - title: YouTube
    url: 
 # - title: 
   # url: 
  #- title: 
   # url: 

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
